# https://towardsdatascience.com/how-to-run-postgresql-using-docker-15bf87b452d4

version: '3.8'

services:
  db:
    container_name: gostack_gobarber
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: gostack_gobarber
    ports:
      - '5432:5432'
    #volumes:

volumes:
  pg_data:
